//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        public int IDE_DOC { get; set; }
        public string NOM_DOC { get; set; }
        public string APE_DOC { get; set; }
        public int IDE_ESP { get; set; }
        public string TEL_DOC { get; set; }
        public string COR_DOC { get; set; }
        public int IDE_DIS { get; set; }
    }
}
